### ISSUE TITLE
Authorizer / User Mixup

### ISSUE THREAD

**Issue by matther2012** [lcdi/Inventory#18]
The authorizer and users are flipped in the database. The authorizer is already set, but it is set to the user

**Comment by temportalflux** [comment]
Explain more?

**Comment by matther2012** [comment]
The table is showing the authorizer as the user and the user as the authorizer

**Comment by temportalflux** [comment]
Oh okay, thats an easy fix.

**Comment by temportalflux** [comment]
Fixed internally, to be committed.
