### ISSUE TITLE
Set types

### ISSUE THREAD

**Issue by matther2012** [lcdi/Inventory#19]
Joe would like set types so that people do not enter extraneous types.

**Comment by temportalflux** [comment]
To clarify, are you saying types should only be able to be added by admins (those who have edit access)?

**Comment by matther2012** [comment]
Correct. Joe does not want people to enter 'Google Glass' as a type. It should fall under Wearable or something. We need to brainstorm the list of types that should be in the inventory

**Comment by temportalflux** [comment]
So the change which needs to be implemented is only allowing those who can edit to add "Other" types.

**Comment by matther2012** [comment]
We need to hard code certain types of our choosing. Allowing users, even people witu edit access may mess with the serial generation.
